### ISSUE TITLE
Unexpected token "name" of value "if" ("end of statement block" expected). in ~/themes/offline-oc-mall-theme/partials/staticmenu/items.htm line 1

### ISSUE THREAD

**Issue by Servery** [OFFLINE-GmbH/oc-mall-theme#21]
I do not know what's wrong… I am on a fresh installation of October CMS and want to try out the default mall theme.

### versions
![0_installedVersions](https://github.com/user-attachments/assets/19868380-2619-4874-8171-a5af55ca56b3)
### find theme
![1_findThemeMall](https://github.com/user-attachments/assets/50998688-92d3-46f9-b350-f204cbe343f6)
### select theme
![2_selectThemeMall](https://github.com/user-attachments/assets/878ede1e-2083-4d1b-a0cc-b1971467e3c2)
### setting install settings (default)
![3_InstallSettingsThemeMall](https://github.com/user-attachments/assets/188785a8-267d-4420-9e41-7a6db264cba9)
### activate
![4_activateThemeMall](https://github.com/user-attachments/assets/76dcfd1c-ab8b-41fa-a143-a1db0a6df35f)
### browse default / frontend page
![5_ERRORThemeMall](https://github.com/user-attachments/assets/7c904627-f7e2-41ab-bc78-dfd491baab7d)

### stacktrace
```
Twig\Error\SyntaxError: Unexpected token "name" of value "if" ("end of statement block" expected) in "/var/www/vhosts/example.com/httpdocs/example.com/october/themes/offline-oc-mall-theme/partials/staticmenu/items.htm" at line 1. in /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/TokenStream.php:74
Stack trace:
#0 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/TokenParser/ForTokenParser.php(41): Twig\TokenStream->expect()
#1 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Parser.php(175): Twig\TokenParser\ForTokenParser->parse()
#2 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Parser.php(84): Twig\Parser->subparse()
#3 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Environment.php(523): Twig\Parser->parse()
#4 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Environment.php(551): Twig\Environment->parse()
#5 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Environment.php(381): Twig\Environment->compileSource()
#6 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Environment.php(343): Twig\Environment->loadTemplate()
#7 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/controller/HasRenderers.php(241): Twig\Environment->load()
#8 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/twig/Extension.php(157): Cms\Classes\Controller->renderPartial()
#9 /var/www/vhosts/example.com/httpdocs/example.com/october/storage/cms/twig/ad/ad649d72ce1a4977890b2ebcbb244f9c.php(46): Cms\Twig\Extension->partialFunction()
#10 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Template.php(360): __TwigTemplate_691ba2d89acd8f05dbcb0e4893b4b37e->doDisplay()
#11 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Template.php(335): Twig\Template->yield()
#12 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#13 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/controller/HasRenderers.php(242): Twig\TemplateWrapper->render()
#14 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/controller/HasRenderers.php(391): Cms\Classes\Controller->renderPartial()
#15 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/twig/Extension.php(197): Cms\Classes\Controller->renderComponent()
#16 /var/www/vhosts/example.com/httpdocs/example.com/october/storage/cms/twig/c8/c810a94119d2056a1ec801f1b1d08b78.php(43): Cms\Twig\Extension->componentFunction()
#17 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Template.php(360): __TwigTemplate_3250ee87b3a799f2bc426992bf90924f->doDisplay()
#18 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Template.php(335): Twig\Template->yield()
#19 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#20 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/controller/HasRenderers.php(242): Twig\TemplateWrapper->render()
#21 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/twig/Extension.php(157): Cms\Classes\Controller->renderPartial()
#22 /var/www/vhosts/example.com/httpdocs/example.com/october/storage/cms/twig/41/4133eafbf97698e4c10d9e12a7cf7bb7.php(84): Cms\Twig\Extension->partialFunction()
#23 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Template.php(360): __TwigTemplate_644661aec9e1ec22be59d381a37f49a9->doDisplay()
#24 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/Template.php(335): Twig\Template->yield()
#25 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#26 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/controller/HasRenderers.php(70): Twig\TemplateWrapper->render()
#27 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/Controller.php(429): Cms\Classes\Controller->renderLayoutContents()
#28 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/Controller.php(226): Cms\Classes\Controller->runPage()
#29 /var/www/vhosts/example.com/httpdocs/example.com/october/modules/cms/classes/CmsController.php(72): Cms\Classes\Controller->run()
#30 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#31 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#32 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#33 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#34 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#35 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#36 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#38 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#40 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#42 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#43 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#45 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#47 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then()
#49 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#50 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#51 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute()
#52 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#53 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#54 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#56 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#57 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#59 /var/www/vhosts/example.com/httpdocs/example.com/october/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#60 /var/www/vhosts/example.com/httpdocs/example.com/october/index.php(42): Illuminate\Foundation\Http\Kernel->handle()
#61 {main}
```

**Comment by Servery** [comment]
I am sure that https://github.com/OFFLINE-GmbH/oc-mall-theme/commit/1217d91e3b60df0fd32aedda1e24c71e9d06f7d4 will solve my problem.

**Comment by tobias-kuendig** [comment]
As @dathwa said, this is because of the old Twig syntax that is not supported in October 3. Use the latest theme version to fix this problem.
